try:
    includedir=__argv__[__argv__.index("--includedir")+1]
except (IndexError, ValueError):
    includedir='.'
__include__(includedir + '/test-config.py')

__addItem__('page1', format='zml', disposition='entry', contents=
'''
[page1]
[folder/page2]
''')

__addItem__('folder/page2', format='zml', disposition='entry', contents=
'''
[page1]
[folder/page2]
''')

#replace the sidebar so we test links in content generated by open-url() (see theme.xsl)
__addItem__('sidebar', format='zml', contents='''
[page1]
[folder/page2]
''')

#replace wiki2html.xsl with a stylesheet that creates an error if a page isn't found (they are all should be)
__addItem__('wiki2html.xsl', format='http://www.w3.org/1999/XSL/Transform', handlesDoctype='wiki',contents='''
<x:stylesheet version="1.0" xmlns:x="http://www.w3.org/1999/XSL/Transform" 
xmlns:wf="http://rx4rdf.sf.net/ns/raccoon/xpath-ext#" xmlns:f="http://xmlns.4suite.org/ext" >
<x:param name='_APP_BASE' />
<x:template match='a[@undefined]'>
    <x:variable name='page' select='f:if(starts-with(@href,$_APP_BASE), substring-after(@href, $_APP_BASE), @href )' />
    <x:if test='not(wf:has-page($page))'>
      <x:message terminate='yes'><x:value-of select='@href'/> not found! with <x:value-of select='$page'/>,<x:value-of select='$_APP_BASE'/></x:message>
    </x:if>
    <a href='{@href}'><x:value-of select='@href'/></a>
</x:template>
</x:stylesheet>''')